[package]
name = "bevy_status_bar_svn"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.16.1"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
